/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorEspacios;
import ec.edu.ups.controlador.ControladorTarifa;
import ec.edu.ups.controlador.ControladorTicketCliente;

import ec.edu.ups.modelo.TicketClienteMomentaneo;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Optional;
import javax.swing.JOptionPane;
import com.lowagie.text.Document;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paul_
 */
public class Tickets extends javax.swing.JInternalFrame {

    private int id;
    private int cont = 1;
    private String ruta = "datos/Ticket.obj";
    private ControladorTicketCliente controladorTicketCliente;
    private ControladorEspacios controladorEspacios;
    private ControladorTarifa controladorTarifa;

    public Tickets(ControladorTicketCliente controladorTicketCliente, ControladorEspacios controladorEspacios, ControladorTarifa controladorTarifa) {

        initComponents();
        this.controladorTicketCliente = controladorTicketCliente;
        this.controladorEspacios = controladorEspacios;
        this.controladorTarifa = controladorTarifa;

        try {
            controladorTicketCliente.cargarDatos();
            controladorEspacios.cargarDatos();
            controladorTarifa.cargarDatos();
        } catch (ClassNotFoundException | IOException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void validarCampos() {

    }

    public void limpiarCbx() {
        cbxEspacioAsignar.removeAllItems();

    }

    private void cargarClientesMomentaneosTbl() {
        String fecha = "";
        DefaultTableModel modelo = (DefaultTableModel) tblClientesMomentaneos.getModel();
        modelo.setRowCount(0);
        if (controladorTicketCliente.clientesM() != null) {
            for (TicketClienteMomentaneo cf : controladorTicketCliente.clientesM()) {

                if (cf.isEstado() == false) {

                    Calendar f = cf.getFechaHoraIngreso();
                    int mes = f.get(Calendar.MONTH) + 1;
                    fecha = f.get(Calendar.DAY_OF_MONTH) + "/" + mes + "/" + f.get(Calendar.YEAR);
                    String hora = "" + f.get(Calendar.HOUR_OF_DAY) + " :" + f.get(Calendar.MINUTE) + " :" + f.get(Calendar.SECOND);
                    Object[] rowData = {cf.getId(), cf.getNombre(), fecha, hora, cf.getTipoVehiculo()};
                    modelo.addRow(rowData);
                    tblClientesMomentaneos.setModel(modelo);
                }

            }
        } else {
            System.out.println("LISTA VACIA");
        }
    }

    /**
     *
     */
    @SuppressWarnings("empty-statement")
    public void cargarClientesTblEgresados() {
        String fecha = "";
        DefaultTableModel modelo = (DefaultTableModel) tblListaClientes.getModel();
        modelo.setRowCount(0);
        if (controladorTicketCliente.clientesM() != null) {
            for (TicketClienteMomentaneo cf : controladorTicketCliente.clientesM()) {
                if (cf.isEstado()) {
                    Calendar f = cf.getFechaHoraIngreso();
                    fecha = f.get(Calendar.DAY_OF_MONTH) + "/" + f.get(Calendar.MONTH + 1) + "/" + f.get(Calendar.YEAR);
                    String hora = "" + f.get(Calendar.HOUR_OF_DAY) + " :" + f.get(Calendar.MINUTE) + " :" + f.get(Calendar.SECOND);;
                    Object[] rowData = {cf.getId(), cf.getNombre(), fecha, hora, cf.getTipoVehiculo(), cf.getTarifa(), cf.getMulta()};
                    modelo.addRow(rowData);
                    tblListaClientes.setModel(modelo);
                }

            }
        } else {
            System.out.println("LISTA VACIA");
        }
    }

    public void cargarCbxEspaciosDisp() {
        limpiarCbx();
        controladorEspacios.espaciosDisponibles().forEach(espacios -> {
            cbxEspacioAsignar.addItem(espacios);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxAutomovil = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtEspActual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxEspacioAsignar = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblClientesMomentaneos = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnImprimirTicket = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestion Clientes Momentaneos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del cliente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Nombre:");

        txtNombre.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Tipo de Vehiculo");

        cbxAutomovil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Motocicleta", "Pesado" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Fecha de Ingreso");

        txtFechaIngreso.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(cbxAutomovil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Espacio Asignado Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel7.setToolTipText("");
        jPanel7.setName(""); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Espacio:");

        txtEspActual.setText("Ninguno");
        txtEspActual.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Espacios disponibles:");

        cbxEspacioAsignar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbxEspacioAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspacioAsignarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Total");

        txtValor.setText("0.0");
        txtValor.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxEspacioAsignar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValor)
                    .addComponent(txtEspActual, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEspActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxEspacioAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida de clientes:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tblClientesMomentaneos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha Ingreso", "Hora Ingreso", "Tipo vehiculo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblClientesMomentaneos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMomentaneosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblClientesMomentaneos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Clientes Momentaneos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha Ingreso", "Hora Ingreso", "Tipo vehiculo", "Tarifa", "Multa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaClientes);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("AGREGAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRetirar.setText("RETIRAR");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnImprimirTicket.setText("Imprimir Ticket General");
        btnImprimirTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnImprimirTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimirTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEspacioAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspacioAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspacioAsignarActionPerformed

    private void tblListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaClientesMouseClicked

        int index = tblListaClientes.getSelectedRow();
        id = Integer.parseInt("" + tblListaClientes.getValueAt(index, 0));
        String nombre = "" + tblListaClientes.getValueAt(index, 1);
        String FechaIngreso = "" + tblListaClientes.getValueAt(index, 2);
        String HoraIngreso = "" + tblListaClientes.getValueAt(index, 3);
        String tipoVehiculo = "" + tblListaClientes.getValueAt(index, 4);
        double tarifa = Double.parseDouble("" + tblListaClientes.getValueAt(index, 5));
        double multa = Double.parseDouble("" + tblListaClientes.getValueAt(index, 6));

        if (tipoVehiculo.trim().equals("Automovil")) {
            cbxAutomovil.setSelectedItem(0);

        } else if (tipoVehiculo.trim().equals("Motocicleta")) {
            cbxAutomovil.setSelectedItem(1);
        } else {
            cbxAutomovil.setSelectedItem(2);
        }

        txtNombre.setText(nombre);
        txtFechaIngreso.setText(FechaIngreso);
        TicketClienteMomentaneo comparar = new TicketClienteMomentaneo();
        comparar.setId(id);
        Optional<TicketClienteMomentaneo> cf = controladorTicketCliente.buscar(comparar);
        TicketClienteMomentaneo c = cf.get();
        txtEspActual.setText("" + c.getEspacioParqueo());
        txtValor.setText("" + tarifa);
    }//GEN-LAST:event_tblListaClientesMouseClicked

    private void tblClientesMomentaneosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMomentaneosMouseClicked
        int index = tblClientesMomentaneos.getSelectedRow();
        id = Integer.parseInt("" + tblClientesMomentaneos.getValueAt(index, 0));
        String nombre = "" + tblClientesMomentaneos.getValueAt(index, 1);
        String FechaIngreso = "" + tblClientesMomentaneos.getValueAt(index, 2);
        String HoraIngreso = "" + tblClientesMomentaneos.getValueAt(index, 3);
        String tipoVehiculo = "" + tblClientesMomentaneos.getValueAt(index, 4);

        if (tipoVehiculo.trim().equals("Automovil")) {
            cbxAutomovil.setSelectedItem(0);

        } else if (tipoVehiculo.trim().equals("Motocicleta")) {
            cbxAutomovil.setSelectedItem(1);
        } else {
            cbxAutomovil.setSelectedItem(2);
        }

        txtNombre.setText(nombre);
        txtFechaIngreso.setText(FechaIngreso);
        txtEspActual.setText("");
        TicketClienteMomentaneo comparar = new TicketClienteMomentaneo();
        comparar.setId(id);
        Optional<TicketClienteMomentaneo> cf = controladorTicketCliente.buscar(comparar);
        TicketClienteMomentaneo c = cf.get();
        txtEspActual.setText("" + c.getEspacioParqueo());
    }//GEN-LAST:event_tblClientesMomentaneosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Calendar fechaIngreso = new GregorianCalendar();
        // String fecha =""+fechaIngreso.get(Calendar.DAY_OF_MONTH)+"/"+fechaIngreso.get(Calendar.MONTH)+"/"+fechaIngreso.get(Calendar.YEAR);

        TicketClienteMomentaneo ticket = new TicketClienteMomentaneo(controladorTicketCliente.generarId(), "Cliente " + controladorTicketCliente.generarId(), cbxAutomovil.getSelectedItem().toString().trim(), fechaIngreso, null, 0, 0, 0.0, false);
        ticket.setEspacioParqueo(Integer.parseInt(cbxEspacioAsignar.getSelectedItem().toString().trim()));

        if (controladorTicketCliente.crear(ticket)) {
            try {
                JOptionPane.showMessageDialog(this, "Cliente registrado con exito");
                controladorTicketCliente.guardarDatos(ruta);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            if (controladorEspacios.AsignarEspacio(Integer.parseInt(cbxEspacioAsignar.getSelectedItem().toString().trim()),
                    "" + controladorTicketCliente.generarId())) {
                try {
                    System.out.println("SE ASIGNO ESPACIO CORRECTAMENTE AL OBJETO " + ticket);
                    controladorEspacios.guardarDatos();
                } catch (IOException ex) {

                }
            }

            cargarClientesTblEgresados();
            cargarClientesMomentaneosTbl();
            cargarCbxEspaciosDisp();

        } else {
            JOptionPane.showMessageDialog(this, "Error al crear Cliente");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    public void limpiar() {
        txtNombre.setText("");
        txtFechaIngreso.setText("");
        txtEspActual.setText("");
        txtValor.setText("");

    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed

        Calendar fechaSalida = new GregorianCalendar();
        // String fecha =""+fechaIngreso.get(Calendar.DAY_OF_MONTH)+"/"+fechaIngreso.get(Calendar.MONTH)+"/"+fechaIngreso.get(Calendar.YEAR);

        TicketClienteMomentaneo comparar = new TicketClienteMomentaneo(id, null, null, null, null, 0, 0, 0.0, false);
        Optional<TicketClienteMomentaneo> t = controladorTicketCliente.buscar(comparar);
        TicketClienteMomentaneo ticket = t.get();
        ticket.setFechaHoraSalida(fechaSalida);
        ticket.setMinutos(controladorTicketCliente.calcularIntervaloTiempo(ticket));

        double total = controladorTicketCliente.calcularTotal(ticket);
        ticket.setTarifa(total);
        ticket.setEstado(true);
        double multa = controladorTicketCliente.generarMulta(ticket);
        ticket.setMulta(multa);

        if (controladorTicketCliente.actualizar(ticket)) {
            try {
                JOptionPane.showMessageDialog(this, "Cliente actualizado con exito");
                controladorTicketCliente.guardarDatos(ruta);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            controladorEspacios.AsignarEspacio(Integer.parseInt(txtEspActual.getText().trim()), "");

            try {
                controladorEspacios.guardarDatos();
            } catch (IOException ex) {
                Logger.getLogger(Tickets.class.getName()).log(Level.SEVERE, null, ex);
            }

            cargarClientesTblEgresados();
            cargarClientesMomentaneosTbl();
            cargarCbxEspaciosDisp();

        } else {
            JOptionPane.showMessageDialog(this, "Error al crear Cliente");
        }

    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int d = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar el  " + txtNombre.getText().trim());
        if (d == JOptionPane.YES_OPTION) {

            TicketClienteMomentaneo comparar = new TicketClienteMomentaneo(id, null, null, null, null, 0, 0, 0.0, false);
            Optional<TicketClienteMomentaneo> cf = controladorTicketCliente.buscar(comparar);
            TicketClienteMomentaneo c = cf.get();

            if (controladorTicketCliente.eliminar(c)) {
                controladorEspacios.AsignarEspacio(Integer.parseInt(txtEspActual.getText().trim()), "");

                try {
                    controladorTicketCliente.guardarDatos(ruta);
                } catch (IOException ex) {
                    Logger.getLogger(Tickets.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    controladorEspacios.guardarDatos();
                } catch (IOException ex) {
                    Logger.getLogger(Tickets.class.getName()).log(Level.SEVERE, null, ex);
                }

                JOptionPane.showMessageDialog(this, "eliminado exitosamente");

            } else {
                JOptionPane.showMessageDialog(this, "no se pudo eliminar ERROR");
            }

            cargarClientesTblEgresados();
            cargarClientesMomentaneosTbl();
            cargarCbxEspaciosDisp();
        } else {
            JOptionPane.showMessageDialog(this, "El cliente todavia no ha");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cargarClientesTblEgresados();
        cargarClientesMomentaneosTbl();
        cargarCbxEspaciosDisp();

    }//GEN-LAST:event_btnListarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarCbxEspaciosDisp();
    }//GEN-LAST:event_formInternalFrameActivated
    public void imprimir() {
        float x = 10;
        float y = 20;
        Document document = new Document(PageSize.A4.rotate());
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("datos/tblClientesMomentaneos" + id + ".pdf"));

            document.open();
            PdfContentByte cb = writer.getDirectContent();

            cb.saveState();

            PdfTemplate pdfTemplate = cb.createTemplate(tblClientesMomentaneos.getWidth(), tblClientesMomentaneos.getHeight());
            Graphics2D g2 = pdfTemplate.createGraphics(tblClientesMomentaneos.getWidth(), tblClientesMomentaneos.getHeight());
            /*g2.setColor(Color.BLACK); 
g2.drawRect(x-2, y-2, table.getWidth()+2, table.getHeight()+2);*/
            tblClientesMomentaneos.print(g2);
            System.out.println("x=" + x + "," + "y=" + y);
            cb.addTemplate(pdfTemplate, x, y);
            g2.dispose();
            cb.restoreState();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        document.close();
        cont++;
    }

    /*public static void main(String[] args) { 
 JTable2Pdf frame = new JTable2Pdf(); 
 frame.pack(); 
 frame.setVisible(true); 
 frame.print(); 
  }*/
    public void cargarBusqueda(TicketClienteMomentaneo c) {
        DefaultTableModel modelo = (DefaultTableModel) tblClientesMomentaneos.getModel();

        modelo.setRowCount(0);
        Calendar f = c.getFechaHoraIngreso();
        String fecha = f.get(Calendar.DAY_OF_MONTH) + "/" + f.get(Calendar.MONTH) + "/" + f.get(Calendar.YEAR);
        String hora = "" + f.get(Calendar.HOUR_OF_DAY) + " :" + f.get(Calendar.MINUTE) + " :" + f.get(Calendar.SECOND);
        Object[] rowData = {c.getId(), c.getNombre(), fecha, hora, c.getTipoVehiculo()};
        modelo.addRow(rowData);
        tblClientesMomentaneos.setModel(modelo);
    }

    public void abrirarchivo(String archivo) {

        try {

            File objetofile = new File(archivo);
            Desktop.getDesktop().open(objetofile);

        } catch (IOException ex) {

            System.out.println(ex);

        }
    }
    private void btnImprimirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirTicketActionPerformed
        String respuesta = JOptionPane.showInputDialog(this, "Ingrese ID de ticket");
        int idTicket = Integer.parseInt(respuesta.trim());

        TicketClienteMomentaneo comparar = new TicketClienteMomentaneo();
        comparar.setId(idTicket);
        Optional<TicketClienteMomentaneo> cf = controladorTicketCliente.buscar(comparar);
        TicketClienteMomentaneo c = cf.get();
        System.out.println("" + c);
        cargarBusqueda(c);

        this.pack();
        this.imprimir();
        abrirarchivo("datos/tblClientesMomentaneos" + id + ".pdf");
    }//GEN-LAST:event_btnImprimirTicketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimirTicket;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox<String> cbxAutomovil;
    private javax.swing.JComboBox<String> cbxEspacioAsignar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblClientesMomentaneos;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTextField txtEspActual;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

}
